server:
  port: 8888
  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:mysql://192.168.88.128:3306/news?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Czc2538755682
    driver-class-name: com.mysql.jdbc.Driver